set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(DHEWM3_PS4 ON CACHE BOOL "Build for OpenOrbis")

if(DEFINED ENV{OO_PS4_TOOLCHAIN})
  set(OO_PS4_TOOLCHAIN "$ENV{OO_PS4_TOOLCHAIN}")
else()
  set(OO_PS4_TOOLCHAIN /opt/openorbis/OpenOrbis/PS4Toolchain)
endif()
if(NOT EXISTS "${OO_PS4_TOOLCHAIN}/lib/crt1.o")
  message(FATAL_ERROR "OpenOrbis toolchain not found: ${OO_PS4_TOOLCHAIN}")
endif()

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_SYSROOT "${OO_PS4_TOOLCHAIN}")
set(CMAKE_C_FLAGS_INIT "-fPIC -D__PS4__ -D__ORBIS__ -D_BSD_SOURCE -isystem ${OO_PS4_TOOLCHAIN}/include")
set(CMAKE_CXX_FLAGS_INIT "-fPIC -D__PS4__ -D__ORBIS__ -D_BSD_SOURCE -D_LIBCPP_HAS_NO_LOCALE -nostdinc++ -isystem ${OO_PS4_TOOLCHAIN}/include/c++/v1 -isystem ${OO_PS4_TOOLCHAIN}/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld -nostdlib -Wl,-pie -Wl,--script=${OO_PS4_TOOLCHAIN}/link.x -Wl,--eh-frame-hdr -Wl,-z,max-page-size=0x4000 -L${OO_PS4_TOOLCHAIN}/lib ${OO_PS4_TOOLCHAIN}/lib/crt1.o")
set(CMAKE_C_STANDARD_LIBRARIES "-lc -lkernel")
set(CMAKE_CXX_STANDARD_LIBRARIES "-lc++ -lc++abi -lunwind -lc -lSceUserService -lScePad -lSceAudioOut -lSceVideoOut -lSceNet -lkernel")
set(CMAKE_FIND_ROOT_PATH "${OO_PS4_TOOLCHAIN}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# The SDK ships SDL2 headers and a static PS4 port.
set(SDL2_INCLUDE_DIR "${OO_PS4_TOOLCHAIN}/include/SDL2" CACHE PATH "PS4 SDL2 headers")
set(SDL2_LIBRARY_TEMP "${OO_PS4_TOOLCHAIN}/lib/libSDL2.a" CACHE FILEPATH "PS4 SDL2 library")
